### ISSUE TITLE
Option encoding behavior causing problems with GlobalSecondaryIndizes

### ISSUE THREAD

**Issue by martinlechner1** [moia-oss/scynamo#246]
First of all: Thank you for the excellent library. We (Autoscout24, hi from Munich) needed to switch from Scanamo, b/c we needed access to some low level operations and this made it really easy.

We discovered however a potential bug:

If a field is part of a Global Secondary Index key-set the `nul` AttributeValue [cannot be put into this field](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/PutItemRequest.html)
  
It causes troubles with the way Option[A] is encoded by default, because DynamoDB will fail with something like:

> One or more parameter values were invalid: Type mismatch for Index Key myNullableKey Expected: S Actual: NULL IndexName: MyGSI

This is the implementation in the library
```
  implicit def optionEncoder[A: ScynamoEncoder]: ScynamoEncoder[Option[A]] = {
    case Some(value) => ScynamoEncoder[A].encode(value)
    case None        => Right(AttributeValue.builder().nul(true).build())
  }
```

I changed it to:

```
  implicit def optionEncoder[A: ScynamoEncoder]: ScynamoEncoder[Option[A]] = {
    case Some(value) => ScynamoEncoder[A].encode(value)
    case None        => Right(null)
  }
```

This however changes the semantics, because in this case the Attribute will not be in DynamoDB at all. I'd argue this even might be desirable because it reduces costs for sparse data sets. What do you think about changing the default behavior in the library?

**Comment by joroKr21** [comment]
Hmm what is the purpose of `nul` if it's treated differently than a missing field 😠 
I think your proposal makes sense but it has to be symmetric with `Decoder`. Is that possible?

**Comment by joroKr21** [comment]
Ok I see that we have:
```scala
override def defaultValue: Option[Option[A]] = Some(None)
```
But somehow using `null` makes me feel bad. Maybe we can filter out `nul` values in map and object decoders?

**Comment by markus1189** [comment]
> Thank you for the excellent library

:heart:  Makes me happy to hear that, and it also makes me happy that @joroKr21 is so actively supporting it after my leave, thank you :)

Also, +1 for this :grin:  :

> somehow using `null` makes me feel bad

Now that Autoscout is using Scynamo as well, maybe we should start a `Adopters` section in the README?

**Comment by martinlechner1** [comment]
Thanks a lot for supporting!

> somehow using null makes me feel bad

dito 👍 

> maybe we should start an Adopters section in the README

If you're looking for increased credibility by this -> Go for it. I'll happily create a PR with a link to our tech blog and add us.
